export const FETCH_PHOTOS_INIT = 'FETCH_PHOTOS_INIT';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_ERROR = 'FETCH_PHOTOS_ERROR';
export const FETCH_PHOTOS_NEXT_INIT = 'FETCH_PHOTOS_NEXT_INIT';
export const FETCH_PHOTOS_NEXT_SUCCESS = 'FETCH_PHOTOS_NEXT_SUCCESS';